#!/bin/sh
set -ex
cd "$(dirname "$0")"

. ./.env.prod

export RETICULUM_SERVER="$HUBS_HOST:4000"
export HUBS_SERVER="$HUBS_HOST:4000"
export ROUTER_BASE_PATH="/spoke"
export NODE_TLS_REJECT_UNAUTHORIZED=0
export BASE_ASSETS_PATH="https://$HUBS_HOST:9090/"
export CORS_PROXY_SERVER="$PROXY_HOST:4080"
export NON_CORS_PROXY_DOMAINS="$PROXY_HOST,$HUBS_HOST"
export INTERNAL_HOSTNAME="$HUBS_HOST"
export THUMBNAIL_SERVER="$THUMBNAIL_HOST:5000"
export BACKEND_URL="$XRCLOUD_BACKEND_URL"

yarn start
