#!/bin/sh
set -ex
cd "$(dirname "$0")"

. ./.env.prod

export RETICULUM_SERVER="$RETICULUM_SERVER"
export HUBS_SERVER="$HUBS_SERVER"
export ROUTER_BASE_PATH="$ROUTER_BASE_PATH"
export NODE_TLS_REJECT_UNAUTHORIZED=$NODE_TLS_REJECT_UNAUTHORIZED
export BASE_ASSETS_PATH="$BASE_ASSETS_PATH"
export CORS_PROXY_SERVER="$CORS_PROXY_SERVER"
export NON_CORS_PROXY_DOMAINS="$NON_CORS_PROXY_DOMAINS"
export INTERNAL_HOSTNAME="$INTERNAL_HOSTNAME"
export THUMBNAIL_SERVER="$THUMBNAIL_SERVER"
export BACKEND_URL="$BACKEND_URL"

yarn start
